version: '3.8'

services:
  strapi:
    image: strapi/strapi:alpine
    restart: unless-stopped
    container_name: strapi
    env_file: .env
    networks: 
      - 'nginx'
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mongo
    volumes:
      - ./app:/srv/app
    # command: 'strapi start'
    # comment command section for development and remove .env NODE_ENV key
networks:
  nginx:
    external:
      name: nginx_reverse_proxy